```{r knitr_setup, include = FALSE}
Sys.setlocale("LC_ALL", "en_US.UTF-8")

frf <- function(...)
    rprojroot::find_root_file(..., criterion = ".editorconfig", path = ".")

knitr::opts_chunk$set(
    cache.path = frf("cache", knitr::opts_knit$get('rmarkdown.pandoc.to'), "/")
)

is_docx_output <- function()
    isTRUE(knitr::opts_knit$get("rmarkdown.pandoc.to") == "docx")
ifelse_is_docx <- function(docx, others) {
    if (is_docx_output())
        docx
    else
        others
}
```

```{r package_bibliography, include = FALSE}
knitr::write_bib(
    c(
        "base",
        "gtsummary"
    ),
    file = frf("bibliography", "rpackages.bib")
)
```

```{r libraries, include = FALSE}
library("english")
library("gtsummary")
library("lubridate")

options(english.UK = FALSE)
```

```{r helper_functions, include = FALSE}
.tbl <- function(tbl, variable, column = "Overall", ...) {
    if (column == "Overall")
        column <- "stat_0"
    gtsummary::inline_text(
        tbl,
        variable = all_of(variable), column = all_of(column), ...
    )
}

.cli_text <- function(...)cli::cli_format_method(cli::cli_text(...))

.pct <- function(x, prec = ".1", symbol = rep_len(TRUE, length(x))) {
    sprintf(
        paste0("%", prec, "f", ifelse(symbol, " %%", "")),
        x * 100
    )
}

.medLU <- function(x, prec=".1") {
    q <- quantile(
        x, probs = c(0.5, 0.25, 0.75), na.rm = TRUE, conf.int = FALSE
    )
    sprintf(
        paste0("%", prec, "f (%", prec, "f, %", prec, "f)"),
        q[1], q[2], q[3]
    )
}

#' return numbers as words
.as.word <- function(x)
    ifelse(x > 12, as.character(x), as.character(as.english(as.numeric(x))))
.as.Word <- function(x).capitalize(.as.word(x))
.capitalize <- function(x) {
    substr(x, 1, 1) <- toupper(substr(x, 1, 1))
    x
}
```

```{r constants, include = FALSE}
sevodensity <- 1.52 # @Hu2021
ORnames <- paste0("OR", 1:2)
```

```{r import, include = FALSE}
agc <- read.csv(frf("data", "agc.csv"))
cases <- read.csv(frf("data", "cases.csv"))
periods <- read.csv(frf("data", "periods.csv"))
flowvapor <- read.csv(frf("data", "flow-vapor-settings.csv"))
```

```{r prepare, include = FALSE}
agc$OR <- ifelse(agc$OR == 21, ORnames[1], ORnames[2])
agc$WeightGain <- agc$FinalWeight - agc$InitialWeight
agc$UsedWeightPerHourSev <- agc$TotalUsedWeightSev / (agc$TotalDurationCasesSev / 60)
agc$InVivoMassTransfer <- agc$WeightGain / agc$TotalUsedWeightSev * 100

agc$AvgDurationSev <- agc$TotalDurationCasesSev / agc$TotalCasesSev

cases$Date <- ymd(cases$Date)
cases <- cases[cases$Date > ymd("2023-10-08") &
               cases$Date < ymd("2024-04-05"),]     # keep only study days
cases <- cases[wday(cases$Date) %in% 2:6,]          # keep only working days
cases <- cases[cases$Duration > 5,]                 # drop test/calibration
cases$OR <- ifelse(cases$Device == "ASDD-0018", ORnames[1], ORnames[2])

# cases per day
ORcases <- vapply(
    split(cases$Date, cases$OR), \(x)median(tapply(x, x, length)), NA_real_
)

periods[c("Start", "End")] <- lapply(periods[c("Start", "End")], as.POSIXct)
```

```{r fit-weight-loss, include = FALSE}
fit.weigth.loss <- lm(LostWeight ~ 0 + DaysStored, data = agc)
```

```{r sevoflurane-consumption-estimation-agc14, include = FALSE}
#' Calculate volatile agent consumption as described in @Biro2015
#'
#' @param flow double, fresh gas flow in L/min
#' @param vapor double, concentration of volatile anaesthetic in Vol%
#' @param duration double, duration of setting in min
#' @param density double(1), density of the used volatile agent
#' @param satvol double(1), saturated gas volume of the used volatile agent
#' @return volatile agent consumption in g
.consumption <- function(flow, vapor, duration, density = sevodensity,
                         satvol = 184) {
    ( ((flow * 1000) * vapor * duration) / (satvol * 100) )  * density
}

flowvapor$Consumption <- .consumption(
    flowvapor$Flow, flowvapor$Vapor, flowvapor$Duration
)
flowvapor$TimeStamp <- ave(
    flowvapor$TimeStamp,
    flowvapor$Case,
    FUN = \(x)as.numeric(difftime(x, x[1], units = "mins"))
)
```

```{r counts, include = FALSE}
nCases <- tapply(agc$TotalCases, agc$OR, sum)
nCasesSev <- tapply(agc$TotalCasesSev, agc$OR, sum)
```

```{r co2eq, include = FALSE}
SevoCO2eq = c(
    waste = 140, # @Nielsen2024
    manufacturing = 143.2928 # @Hu2021, supplement 1-s2.0-S0921344921000185-mmc2.xlsx, Table "CO2-Eq (Route-C):E37" 886.5143 and Table "CO2-Eq (Route-E):E38" 143.2928 - Route B
    # 20.625
    # Presentation Baxter LCA: Life Cycle Assessment of Anaesthetic Gas Capture in the Operating Room using ContraFluran Tom Costelloe, Michael Collins, Doyin Oladele and Simon Aumônier 25/01/2022
    # source should be: "Life Cycle Greenhouse Gas Emissions of Anaesthetic Drugs", Sherman et al. Anesthesia & Analgesia. 114(5):1086-1090, May 2012; could not find direct number; maybe could be calculated with LCA software given the ingredients
)

CONTRAfluranCO2eq <- 66.6 # @Costelloe2022, Scenario UK, page 14

AGSSkWh <- 0.1 # @Schuster2023
kWhCO2eq <- 0.485 # @Schuster2023

TotalUsedWeightSev <- sum(agc$TotalUsedWeightSev)
TotalWeightGain <- sum(agc$WeightGain)
TotalRecoveredSev <- NA # TODO, response ZeoSys needed
CaptureEfficiency <- TotalRecoveredSev / TotalUsedWeightSev
AGC14EstimatedUsedWeightSev <- sum(flowvapor$Consumption)

agc$ProportionalCaptureEfficiency <-
    (agc$WeightGain / TotalWeightGain * TotalRecoveredSev) /
    agc$TotalUsedWeightSev
agc$ProportionalCapturedWeightSev <-
    (agc$WeightGain / TotalWeightGain * TotalRecoveredSev)

TotalDurationCases <- sum(agc$TotalDurationCases)

TotalCO2eq <- c(
    CONTRAfluran = unname(
        # manufacturing
        TotalUsedWeightSev * SevoCO2eq["manufacturing"] +
        # waste
        (TotalUsedWeightSev - TotalRecoveredSev) * SevoCO2eq["waste"] +
        # CONTRAfluran production/transportion/desorption
        (TotalWeightGain * CONTRAfluranCO2eq) -
        # saving
        TotalRecoveredSev * SevoCO2eq["manufacturing"]
    ),
    AGSS =
        TotalUsedWeightSev * sum(SevoCO2eq) +
        TotalDurationCases * AGSSkWh * kWhCO2eq
)

ORCO2eq <- tapply(agc, agc$OR, function(aa) {
    UsedSev <- sum(aa$TotalUsedWeightSev)
    RecoSev <- TotalRecoveredSev * sum(aa$WeightGain) / TotalWeightGain

    # manufacturing
    UsedSev * SevoCO2eq["manufacturing"] +
    # waste
    (UsedSev - RecoSev) * SevoCO2eq["waste"] +
    # CONTRAfluran production/transportion/desorption
    (sum(aa$WeightGain) * CONTRAfluranCO2eq) -
    # saving
    RecoSev * SevoCO2eq["manufacturing"]
})
```

```{r table1-build, include = FALSE, message = FALSE}
theme_gtsummary_compact(font_size = 8L)

tbl_cases <- agc |>
    mutate(OR = ifelse(OR == ORnames[1],
        paste(ORnames[1], "(ENT)"), paste(ORnames[2], "(Neurosurgery)"))) |>
    select(
        OR,
        TotalCases,
        TotalCasesSev,
        TotalDurationCasesSev,
        AvgDurationSev
    ) |>
    dplyr::mutate_at(vars(matches("TotalDuration")), function(x)x / 60) |>
    tbl_summary(
        by = OR,
        missing_text = "(Missing)",
        type = list(
            TotalCases ~ "continuous",
            TotalCasesSev ~ "continuous",
            TotalDurationCasesSev ~ "continuous",
            AvgDurationSev ~ "continuous"
        ),
        label = list(
            TotalCases ~ "Total number of cases",
            TotalCasesSev ~ "Number of inhaled anaesthesia cases",
            TotalDurationCasesSev ~ "Total duration of inhaled anaesthesia [h]",
            AvgDurationSev ~ "Average duration of inhaled anaesthesia [min]"
        ),
        digits = all_continuous() ~ 1
    ) |>
    add_p()

tbl_weights <- agc |>
    select(
        OR,
        WeightGain,
        InVivoMassTransfer,
        ProportionalCapturedWeightSev,
        ProportionalCaptureEfficiency
    ) |>
    dplyr::mutate(
        ProportionalCaptureEfficiency = ProportionalCaptureEfficiency * 100
    ) |>
    tbl_summary(
        by = OR,
        missing_text = "(Missing)",
        type = list(
            WeightGain ~ "continuous",
            InVivoMassTransfer ~ "continuous",
            ProportionalCapturedWeightSev ~ "continuous",
            ProportionalCaptureEfficiency ~ "continuous"
        ),
        label = list(
            WeightGain ~ "Weight gain [g]",
            InVivoMassTransfer ~ "*In vivo* mass transfer [%]",
            ProportionalCapturedWeightSev ~ "Proportional sevoflurane captured [g]",
            ProportionalCaptureEfficiency ~ "Proportional capture efficiency [%]"
        ),
        digits = all_continuous() ~ 1
    ) |>
    add_p()

tbl_weights_overall <- add_overall(tbl_weights)

tbl_sevo_consumption <- agc |>
    select(
        OR,
        TotalUsedWeightSev,
        UsedWeightPerHourSev
    ) |>
    tbl_summary(
        by = OR,
        missing_text = "(Missing)",
        type = list(
            TotalUsedWeightSev ~ "continuous",
            UsedWeightPerHourSev ~ "continuous"
        ),
        label = list(
            TotalUsedWeightSev ~ "Total sevoflurane weight used [g]",
            UsedWeightPerHourSev ~ "Average sevoflurane weight used per hour inhaled anaesthesia [g.h^-1^]"
        ),
        digits = all_continuous() ~ 1
    ) |>
    add_p()

tbl1 <- tbl_stack(
    tbls = list(
        tbl_cases, tbl_sevo_consumption, tbl_weights
    ),
    group_header = c(
        "(A) Case summary",
        "(B) Sevoflurane consumption",
        "(C) Anaesthetic gas canister characteristics"
    )
) |>
## indent variable names and missing
modify_table_styling(columns = "label", text_format = "indent") |>
modify_table_styling(
    rows = row_type %in% c("missing", "level"),
    columns = "label",
    text_format = "indent2"
) |>
modify_spanning_header(c("stat_1", "stat_2") ~ "**Operating rooms**") |>
modify_caption(
    paste0(
        "ENT: ear, nose and throat surgery; ",
        "Characteristics of all ", nrow(agc), " anaesthetic gas canisters. ",
        "Cases, duration, etc. are given as per canister."
    )
)
```
