# Introduction

The anthropogenic climate crisis is the largest threat to global health [@Daalen2022].
However, the health-care sector itself is responsible for 5-10 % of greenhouse gas emissions [@Hu2021].
A relevant part of these emissions are caused by volatile anaesthetics (VAs) used in anaesthesia and intensive care [@MacNeill2017;@Hu2021].

Active charcoal absorbers can be attached to the exhaust port of the anaesthesia machines to decrease these emssions and capture VAs.
Using absorbers that allow the recapture of the VAs has the
additional benefit of being able to reuse the substances.

A previous study by Hinterberg et al. [@Hinterberg2022], which investigated the efficiency of the CONTRAfluran^TM^ (ZeoSys medical, Luckenwalde, Germany) vapour-capturing system for VAs in the operating room (OR), found that only 25 % of the vapourised desflurane could be recaptured.
However, as Kalmar et al. pointed out [@Kalmar2023], the desorption process to recapture the substances from the absorber is highly dependent on the saturation level of the CONTRAfluran^TM^ anaesthetic gas canister (AGC), with a higher capture efficiency for full charcoal absorbers.
Therefore, it can be assumed that a higher efficiency could be obtained, when AGCs are used to a higher saturation level than the 15 % in the study by Hinterberg et al. [@Kalmar2023; @Hinterberg2022].
This might be one reason why Gandhi et al. reported a significantly higher capture efficiency of 43-51 % using SageTech Medical's Volatile Capture Device (SageTech Medical, Paignton, UK) for sevoflurane, even though one would expect that the capture efficiency for sevoflurane would be lower in comparison to desflurane, due to the higher blood-gas coefficients and metabolism rate of sevoflurane [@Gandhi2023].
Mulier et al. weighed the AGC before, during and after anaesthesia for
laparoscopic surgery and determined an *in vivo* mass transfer (ratio of absorber
weight gain to consumed weight of sevoflurane) of 45 %
[@Mulier2024].
But as the system used by Gandhi et al. included an additional anaesthetic gas scavenging system (AGSS) to capture the VA and Mulier et al. did not report the results of the desorption process, it remains unknown how efficient vapour capture systems for sevoflurane without an AGSS connected can be when used to maximum saturation levels [@Gandhi2023; @Mulier2024].
Therefore, we conducted this exploratory study to investigate the efficiency of passive vapour capture systems for sevoflurane and the entire recapture process when vapour capture systems for sevoflurane are used to higher saturation levels.
