# Methods

In this prospective single-center observational study we collected
`r nrow(agc)` consecutive CONTRAfluran anaesthetic gas canisters from
`r paste(format(range(c(agc$Start, agc$End)), "%B %Y"), collapse = " to ")`
in two different operating rooms.

In the first operating room we mainly took care for patients for ear, nose and throat surgery.
Generally the first and second case each day were children where we did inhaled inductions with a fresh gas flow in the range of the minute ventilation of the child.
Mostly we used a supraglottical airway in the five to six cases per day.

In the second operating room we did mainly tracheal intubations for neurosurgical spine surgery and had around two cases a day.

Following our standard operating procedures a minimal or metabolic flow (< 0.5 L/min, mostly 0.35 L/min) was used during the steady-state phase in all cases.

We used the Draeger connect software (Draeger Medical Deutschland GmbH, Luebeck, Germany) to determine the number and duration of anaesthesia cases.

Volatile anaesthesia was applied using Draeger Perseus A500 anaesthesia machines equipped with Draeger D-Vapor 3000 (Draeger Medicine Deutschland GmbH, Luebeck, Germany).
The vapor weighs more than nine kg.
A scale that was precise enough to measure more than 9 kg with a precision of a few grams was not available.
That's why we decided to weigh the sevoflurane bottles before and after maximum filling of the vapor and use the difference in weigh to record the sevoflurane consumption.
The vapor was maximum filled before we attach the first CONTRAfluran anaesthetic gas canister (AGC; ZeoSys medical, Luckenwalde, Germany).
If the CONTRAfluran AGC was exhausted, visible by the red LED and an acoustic warning signal of the SENSOfluran sensor unit (ZeoSys medical, Luckenwalde, Germany), the vapor was again filled to the maximum.
In case a new bottle of sevoflurane was opened, it was attached to a non-study vapor to lose any excess pressure before the study vapor was filled.
To determine the amount of captured gas we weighed the CONTRAfluran ACG before usage and after it was exhausted.
All ACGs were closed and stored in a zip lock bag.

We measured the weight of the ACG and sevoflurane bottles with a precision scale (Kern PCB 2500-2; Kern&Sohn GmbH, Balingen-Frommern; Germany; maximum weight=2500g; d=0.01g).

All data processing and statistical analyses were performed using R version
`r paste0(sessionInfo()$R.version[c("major", "minor")], collapse = ".")`
[@R-base].

Summary tables were generated using the *gtsummary* package [@gtsummary; @R-gtsummary].
All data and analysis can be found at https://github.com/umg-minai/vct-or **TODO** (add zenodo citation link).

The Ethics Committee at the University Medicine Greifswald approved this study protocol (reference number: BB 102/23).
