# Methods

## Ethics approval

The study was approved by the ethics committee of the University Medicine Greifswald
(Chairperson: Prof. Dr. M. Dörr;
reference number: `r rmarkdown::metadata[["ethics_committee"]][["reference_number"]]`;
approval date: `r rmarkdown::metadata[["ethics_committee"]][["approval_date"]]`).

## Definitions

We apply the taxonomy recently introduced by Gandhi et al. [@Gandhi2024].
Briefly, the capture efficiency refers to the entire recapture process and
includes the mass of VA that was used in comparison to the mass that was
eventually recovered from the AGC and could be reused.
Proportional capture efficiency is the calculated efficiency for each
individual AGC.
The *in vivo* mass transfer describes the increase in mass of the
AGC in proportion to the mass of the VA used in a clinical setting.

## Setting

We collected a total of `r nrow(agc)` consecutive CONTRAfluran^TM^ AGCs in two different ORs in this prospective single-centre exploratory observational study.

The first OR (referred to as `r ORnames[1]`), was dedicated to
ear, nose and throat surgery.
Here, a median number of `r .as.word(round(ORcases[1]))` cases per day
were treated, mostly with supraglottic airways.
All cases were inducted and emerged from anaesthesia in the OR.
The first and second case each day were generally children,
where we did inhaled inductions with a fresh gas flow in the range of
the minute ventilation of the respective child.
The following cases were mostly adults.

The second OR (referred to as `r ORnames[2]`) was dedicated to
neurosurgical spine surgery.
Here, the median number of cases was `r .as.word(round(ORcases[2]))` per day
and the patients were mostly adults who were intubated.
The first case was always inducted in the OR,
the following cases rarely in a special induction room where no AGC was installed.
All cases emerged from anaesthesia in the OR.

All anaesthesia cases were performed at the discretion of the
anaesthesiologists in charge in clinical routine
according to our local standard operating procedures.
Following these, a minimal or metabolic flow (< 0.5&nbsp;l·min^-1^, mostly 0.3&nbsp;l·min^-1^) was used during the steady state phase in all cases.
We did recorded neither the patient data, the type of anaesthesia,
the induction strategy nor the airway used because of the exploratory, pragmatic
and anonymous character of the study.

We used the Draeger connect software (Draeger Medical Deutschland GmbH, Luebeck, Germany) to determine the number, duration and type of anaesthesia cases.

## Consumption and weight measurement

Balanced anaesthesia with VAs was given using Draeger Perseus A500 anaesthesia machines equipped with bypass vaporizers of the type Draeger D-Vapor 3000 (Draeger Medicine Deutschland GmbH, Luebeck, Germany).
The AGCs were permanently connected to the exhaust port of the anaesthesia machines, which work in a passive mode, without an AGSS connected.
We weighed the sevoflurane (SEVOrane, AbbVie Deutschland GmbH & Co. KG, Mainz, Germany) bottles before and after maximum filling of the vaporizer and used the difference in weight to record the sevoflurane consumption.
The vaporizers were filled to the maximum before we attached the first CONTRAfluran^TM^ AGC (ZeoSys medical, Luckenwalde, Germany) and started our recordings.
During the study period, almost every day the two vaporizers were filled completely and the sevoflurane bottle weight difference measured by the study team (NM and SK), which was not involved in the anaesthesia.

In the case where a new bottle of sevoflurane was opened, it was initially attached to a non-study vaporizer to lose any excess pressure, and was weighed before the study vaporizer was filled.

Each AGC was only changed after it had been exhausted.
This was made visible by a red LED and an acoustic warning signal of the SENSOfluran^TM^ sensor unit (ZeoSys medical, Luckenwalde, Germany).
Subsequently, we refilled the vaporizer to its maximum and measured the weight
difference of the sevoflurane bottle, again.
The weight difference was counted as consumption for the just exhausted AGC.

The weight gain of an AGC was determined by weighing the AGC before usage and after it had been exhausted to determine the *in vivo* mass transfer (ratio of absorber
weight gain to consumed weight of sevoflurane).
Each exhausted AGC was recapped and stored in a closed plastic zip-lock bag.

ZeoSys needs at least 20 AGCs for a single desorption process.
Before returning the AGCs to ZeoSys, we weighed all AGCs again
to determine any potential weight loss.

All weight measurements were done with a precision scale
(Kern PCB 2500-2; Kern\&Sohn GmbH, Balingen-Frommern; Germany; maximum weight&nbsp;=&nbsp;2500&nbsp;g;&nbsp;d&nbsp;=&nbsp;0.01&nbsp;g)

ZeoSys stored all AGCs for a further four weeks at least, due to regulatory reasons.
Before starting the desorption and recovery process they weighed all AGCs
(Sartorius Cubis II MCA5201S-2S00-0; Sartorius AG, Göttingen; Germany; maximum weight = 5200 g; d = 0.1 g).
Afterwards, they sent us the information about the total amount of sevoflurane recovered from all 20 AGCs.

The capture efficiency was then determined by calculating the
total amount of sevoflurane recovered relative to the amount used [@Gandhi2024].
We compare the total amount of sevoflurane recovered to the individual weight of
each AGC, divided by the total weight of all AGCs, to get the proportional
capture efficiency.

## Outcome

The primary outcome was the amount of recovered sevoflurane reported by ZeoSys.
The secondary outcomes were the difference between the *in vivo* mass transfer and the recapture rate reported by ZeoSys, the difference in the sevoflurane recovery between both ORs
and the weight loss of the AGC during storage.

## Data processing and statistical analysis

All data processing and statistical analyses were performed using R version
`r paste0(sessionInfo()$R.version[c("major", "minor")], collapse = ".")`
[@R-base].
The two-sided Wilcoxon rank-sum test was used for statistical comparison.
A *p*-value less than 0.05 was considered to be statistically significant.
Summary tables were generated using the *gtsummary* package [@Sjoberg2021].
All data and analysis can be found at https://github.com/umg-minai/vct-or [@vctordata].
