# Discussion

@hinterberg2022: meisten Filter leer (nur 8 % der möglichen Füllmenge), neuer Filter je Patient, 70 % weight gain attributable to desflurane, höhere MAC und längere Dauer mit geringerer recapture rate assoziiert, laut Supplement, hoher FGF 0.8 l/min

Hu et al TIVA vs IA + VCT

vgl. Cost Effizienz ggü. AGFS u. CO2-Effizienz ggü. AGFS

Leckage can't captured
Retention in patient can't captured

Kalmar et al 2023: An ISO
14040-compliant life cycle analysis conducted by an inde-
pendent organisation (ERM) on behalf of Baxter (Deerfield, IL,
USA; full data are available for presentation by Baxter on
request) reveals that the carbon footprint associated with
canister production, transport, desorption, and recycling/
disposal, based on 2020 UK carbon intensity assumptions,
equals total emissions of 45.4 kg of CO2e per 1 kg of captured
volatile anaesthetics.

@Dexter2023 simulation of the dependency of the vct recapture efficiency on the
FGF and duration, as expected: lower FGF lower relative recapture (less wastage)
and longer duration yield lower relative recapture (more saturation);

simulated values for 8 l/min induction for 15 min, and 0.5 l/min FGF for an hour (vapor set to 3.7% Sevo?; no information about etSevo) are not comparable to our setting: 4-6 l/min for 3-5 min for inhalative induction (or 0.5 l/min for a few minutes after intravenous induction), 0.3 l/min maintenance); 30 ml Sevo consumption in @Dexter2023 vs ~ 10 ml/h in our setting

## Limitations

Vapor verliert in 24 h < 0.5 ml Sevo (das nicht über den Filter geht) und mgl. Schwankungen bei maximaler Füllung.
Tropfen in "Einfüllstutzen", damit evtl. Überschätzung des Verbrauchs.
