# Supplement

## Table of anaesthetic gas canisters

```{r tableagc, echo = FALSE, message = FALSE, caption = "Details of anaesthetic gas canisters."}
library("flextable")

typology <- data.frame(
    col_keys = c(
        "Id", "OR", "InitialWeight", "FinalWeight", "WeightGain",
        "TotalCases", "TotalCasesSev",
        "TotalDurationCases", "TotalDurationCasesSev", "AvgDurationSev",
        "TotalUsedWeightSev", "UsedWeightPerHourSev",
        "InVivoMassTransfer"
    ),
    what = c(
            "Id", "OR", "Weight [g]", "Weight [g]", "Weight [g]",
            "Cases", "Cases",
            "Duration [h]", "Duration [h]", "Duration [h]",
            "Sevoflurane consumption", "Sevoflurane consumption",
            "MT [%]"
    ),
    measure = c(
            "Id", "OR", "Initial", "Final", "Gain", "Total", "Sevo",
            "Total", "Total Sevo", "Avg Sevo",
            "Total [g]", "Avg [g/h]", "MT [%]"
    ),
    stringsAsFactors = FALSE
)

agc[c(
    "Id", "OR", "InitialWeight", "FinalWeight", "WeightGain",
    "TotalCases", "TotalCasesSev",
    "TotalDurationCases", "TotalDurationCasesSev", "AvgDurationSev",
    "TotalUsedWeightSev", "UsedWeightPerHourSev",
    "InVivoMassTransfer")] |>
    knitr::kable(
        digits = 1,
        col.names = c(
            "Id", "OR",
            "W~i~", "W~f~", "W~d~",
            "N", "N~sev~",
            "D", "D~sev~", "D~avg~",
            "C~sev~", "C~avg~",
            "MT"
        ),
        caption = paste0(
            "Details of anaesthetic gas canisters. ",
            paste0(
                c(
                    "C~sev~: total used sevoflurane [g]",
                    "C~avg~: average used sevoflurane [g/h]",
                    "D: total duration [h]",
                    "D~sev~: total duration of sevoflurane cases [h]",
                    "D~avg~: average duration of sevoflurane cases [h]",
                    "Id: lot number",
                    "MT: in vivo mass transfer [%]",
                    "N: total number of anaesthesia cases",
                    "N~sev~: total number of sevoflurane cases",
                    "OR: operation room",
                    "W~d~: weight gain",
                    "W~f~: final weight",
                    "W~i~: initial weight"
                ),
                collapse = "; "
            )
        )
    )
```

## R session information


```{r sessioninfo}
sessionInfo()
```


## Git commit hash


```{r gitcommithash, echo = FALSE}
sprintf("Git commit revision: %s", system("git rev-parse HEAD", intern = TRUE))
```

